# Getting started
# See https://snapcraft.io/docs/getting-started
# Snapcraft references
# See https://snapcraft.io/docs/snapcraft-yaml-reference
name: ctrlx-docker-ignition
version: "1.0"
base: core22
summary: Provides Inductive Automation Ignition to ctrlX Container Engine
description: |
    This snap contains the docker image 'inductiveautomation/ignition:latest'.
    The files 'image.tar', 'docker-compose.yml' and 'docker-compose.env' are provided via content-interface 'docker-compose'.
    The content-interface 'docker-volumes' provides the container access to a directory inside this snap with write permissions.
grade: stable
confinement: strict

parts:
    docker-compose:
        plugin: dump
        source: ./docker-compose
        organize:
            "*": docker-compose/${SNAPCRAFT_PROJECT_NAME}/

slots:
    docker-compose:
        interface: content
        content: docker-compose
        source:
            read:
                - $SNAP/docker-compose/${SNAPCRAFT_PROJECT_NAME}

    docker-volumes:
        interface: content
        content: docker-volumes
        source:
            write:
                - $SNAP_DATA/docker-volumes/${SNAPCRAFT_PROJECT_NAME}
